### ISSUE TITLE
תרגול פונקציות

### ISSUE THREAD

**Issue by cozohar** [tocodeil/html5-course-examples#5]
Hi,

Can you please show me the solution for the second exercise?
I'm not sure how to solve it with only changing the writeText function.

Thanks,
Zohar

**Comment by ynonp** [comment]
The trick is we use the return value of `writeText` as input to `addEventListener`. Since `addEventListener` expects a function as its second argument, `writeText` must in turn return a function.

That function is used as an event handler so it receives only an event description object (of which it has no use) and can print the text provided to the code that created it.

You can try again using the hint or find a working version here:
http://codepen.io/ynonp/pen/JbVRBb
